language: haskell

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.10.2

# ghc: 7.10

before_install:
  - export PATH=/opt/cabal/1.22/bin:/opt/ghc/bin:$PATH && which cabal && which ghc

install:
  - cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
